version: "3.8"

services:

  ana:
    image: ${SERVICE_NAME}
    build:
      context: .
    volumes:
      - ${DOCKER_WORKDIR}:/app
    environment:
      DATABASE_URL: "postgres://ana-user:not-safe-at-all@postgres:5432/ana-db?pool_min_conns=5&pool_max_conns=5"
    depends_on:
      - postgres

  postgres:
    image: postgres
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    volumes:
      - ${DOCKER_WORKDIR}/repository/pgx/migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB:       "ana-db"
      POSTGRES_USER:     "ana-user"
      POSTGRES_PASSWORD: "not-safe-at-all"
